name: Release Pipeline

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Backend
        run: |
          cd apps/backend
          npm install
          npm run build

      - name: Deploy Backend
        run: ./infra/scripts/deploy-backend.sh

      - name: Publish Dart SDK
        uses: dart-lang/setup-dart@v1
      - run: |
          cd libs/dto
          dart pub publish --force

      - name: Generate Release Notes
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true